import type { EditorThemeClasses } from "lexical"

export const lexicalTheme: EditorThemeClasses = {
  paragraph: "mb-2 text-sm leading-relaxed text-foreground",
  heading: {
    h1: "text-xl font-bold text-foreground mb-3 mt-4 first:mt-0",
    h2: "text-lg font-semibold text-foreground mb-2 mt-3 first:mt-0",
    h3: "text-base font-medium text-foreground mb-2 mt-2 first:mt-0",
  },
  text: {
    bold: "font-bold",
    italic: "italic",
    strikethrough: "line-through",
    underline: "underline",
    code: "bg-muted px-1.5 py-0.5 rounded text-xs font-mono",
  },
  link: "text-primary underline cursor-pointer hover:text-primary/80",
  list: {
    ul: "list-disc ml-5 mb-2 space-y-1",
    ol: "list-decimal ml-5 mb-2 space-y-1",
    listitem: "text-sm text-foreground",
    nested: {
      listitem: "list-none",
    },
    listitemChecked: "line-through text-muted-foreground",
    listitemUnchecked: "",
  },
  quote: "border-l-2 border-border pl-3 italic text-muted-foreground my-2",
  code: "block bg-muted p-3 rounded-md text-xs font-mono overflow-x-auto my-2",
  codeHighlight: {
    atrule: "text-purple-500 dark:text-purple-400",
    attr: "text-blue-500 dark:text-blue-400",
    boolean: "text-orange-500 dark:text-orange-400",
    builtin: "text-cyan-500 dark:text-cyan-400",
    cdata: "text-gray-500 dark:text-gray-400",
    char: "text-green-500 dark:text-green-400",
    class: "text-yellow-500 dark:text-yellow-400",
    "class-name": "text-yellow-500 dark:text-yellow-400",
    comment: "text-gray-400 dark:text-gray-500 italic",
    constant: "text-orange-500 dark:text-orange-400",
    deleted: "text-red-500 dark:text-red-400",
    doctype: "text-gray-500 dark:text-gray-400",
    entity: "text-red-500 dark:text-red-400",
    function: "text-blue-500 dark:text-blue-400",
    important: "text-red-500 dark:text-red-400 font-bold",
    inserted: "text-green-500 dark:text-green-400",
    keyword: "text-purple-500 dark:text-purple-400",
    namespace: "text-gray-500 dark:text-gray-400",
    number: "text-orange-500 dark:text-orange-400",
    operator: "text-foreground",
    prolog: "text-gray-500 dark:text-gray-400",
    property: "text-blue-500 dark:text-blue-400",
    punctuation: "text-foreground",
    regex: "text-green-500 dark:text-green-400",
    selector: "text-green-500 dark:text-green-400",
    string: "text-green-500 dark:text-green-400",
    symbol: "text-purple-500 dark:text-purple-400",
    tag: "text-red-500 dark:text-red-400",
    url: "text-blue-500 dark:text-blue-400 underline",
    variable: "text-red-500 dark:text-red-400",
  },
}
